version: "3.9"

services:
  app:
    image: ghcr.io/daniel-dief/alise-ai:latest
    container_name: alise-ai
    command: python -m app.main
    ports:
      - "5959:5959"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      backend_network:
        ipv4_address: ${APPIP}

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASSWORD}
      POSTGRES_DB: ${DBNAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      backend_network:
        ipv4_address: ${DBHOST}

volumes:
  postgres_data:

networks:
  backend_network:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}